### ISSUE TITLE
subdirectory-filter corrupting repository with nested directory named like its parent

### ISSUE THREAD

**Issue by zyzyzyryxy** [newren/git-filter-repo#37] opened 2019-12-27 17:12 UTC
Hello, I am trying to split repository into subprojects and got an unexpected behaviour.
Roughly my repo has directory structure like this:
```
code/
  src/
  (some other files and directoriess)
tests/
  tests/
    src/
  test-runner/
```
When I do `git --subdirectory-filter tests` I expected to end up with:
```
tests/
  src/
test-runner/
```
Instead, I got:
```
tests/
  src/
test-runner/
src/
```
Project root got all the files and directories from the original tests/ and tests/tests/ directories mixed instead of only the ones from tests/.

If you need a more formal reproduction steps or an example repo, I can provide those after the weekend.

**Comment by newren** [comment] 2019-12-27 20:08
Thanks for the report.  This could be a duplicate of issues #3 and #35 ; even though the flags are a bit different the underlying bug could cause this issue here too.  Those two bugs have workarounds listed in them, but more importantly, I pushed up a fix for the underlying issue on Christmas and am just awaiting confirmation from others that it fixes their problem before closing out those issues.

What version of filter-repo are you using?  Does it include the fixes I pushed two days ago, by chance?  If the latest version of filter-repo doesn't fix your problem, an example repo would be very helpful.

**Comment by zyzyzyryxy** [comment] 2019-12-28 09:48
I've seen #3, downloaded new version and actually found this behaviour only
afterwards.

I did struggle with other problems before the update, but intentionally
left those out of this report to not make confusion. My case is more
complex, so I did simplify to confirm.that the bug is still there in the
newest version.

pt., 27 gru 2019, 21:08 użytkownik Elijah Newren <notifications@github.com>
napisał:

**Comment by newren** [comment] 2019-12-28 18:55
Thanks for trying out the latest version.  I'm scratching my head trying to figure out what else might cause this, so an example repo would be very helpful.

**Comment by zyzyzyryxy** [comment] 2019-12-30 10:08
As for now, my attempt to reproduce the error in a smaller repo failed, though I found another strange behaviour - this time reproducible I hope (see #38). I'll get back to this one in a few days when I have more time.

**Comment by newren** [comment] 2019-12-30 17:13
Thanks for trying to come up with a smaller testcase.  I tried a couple simple example repos that matched your structure as well, but none of them worked for me to reproduce either.  I'll await your further investigations (or you could just give me access to your real repo & steps to reproduce, so long as it's something you're allowed to have me take a look at).

**Comment by zyzyzyryxy** [comment] 2020-01-09 10:51
Sorry for taking so long to answer.
I cannot grant you access to the repo as it is corporate one.
Meanwhile preparation of the test case is of low priority unfortunately, but I do hope to get back to it soon-ish. For now, thanks to explanations from #24 (which did happen in my case too), I was able to work around the issue. 

My workaround was changing repositories I am exporting, thus not needing to export this specific path. Not really applicable for others probably :-)

**Comment by newren** [comment] 2020-01-09 19:45
Well, I'm glad the fixes for #24 helped you out at least.  I understand shifting priorities; I'll leave this open for now and hope you get a chance to find some steps to reproduce at some point and pass them along.

**Comment by newren** [comment] 2020-02-10 21:59
May possibly have been caused by #53, in which case this should be fixed.  Any chance you could retest?

**Comment by newren** [comment] 2020-03-21 21:33
Rather than leave this open forever, and since it may likely have been caused by #53, I'm going to go ahead and close.  Do let me know, though, if you're able to reproduce with a version with #53 fixed and/or come up with any steps for duplicating this problem.

**Closed by newren** 2020-03-21 21:33 UTC
