### ISSUE TITLE
Query on syntax for --paths-from-file lines.

### ISSUE THREAD

**Issue by richardck** [newren/git-filter-repo#77] opened 2020-04-21 16:28 UTC
I've got filter-repo up and running.
I have quite a long list of files and folders that I want to filter out of one old repo and into a fresh new one, so I'm using --paths-from-file.  However, although the files in the source repo are in four folders within the source repo only one of those is appearing in the target.  It is the only one that is specified as *only* the folder name - all the others have a folder name and file-name, sometimes with wildcard.

ie 
panels
Works, and all the following don't.  (Where "works" means that it and all its sub-folders appear in the target).

config/alarms
config/devicetypes/device_description.xslt
config/devicetypes/MCR_CC_OUTPUT.xml
config/applications.*
Source/include/com32.h

"config" is a folder.
"config/alarms" is a folder, all the others are files, sometimes with wildcard extensions.

I am assuming I've got the syntax wrong somewhere and I'd appreciate a pointer on how to get it right.

**Comment by newren** [comment] 2020-04-22 00:34
I haven't developed anything on Windows in over two decades and have no system to test on, and the description alone isn't enough for me to know what the issues are, but I do have some ideas that might be helpful in helping you track this down:

As pointed out in the manual, by default every line of the file passed to --paths-from-file is assumed to be a literal pathname.  You can prefix with `literal:` to be explicit, but if you have no `glob:` or `regex:` prefix on the line, then the code assumes you are specifying a literal directory or file name.  Thus unless you have _a file_ named `config/applications.*`, then that line isn't going to do what you want; `glob:config/applications.*` is more likely what you intended.  Make sure you don't leave any leading or trailing whitespace on your lines either.

I also notice you have mostly lowercase filenames, but 'Source' and e.g 'MCR_CC_OUTPUT' in the examples, suggesting case might have been mixed.  The com32.h suggests that you might unfortunately be stuck on a broken filesystem (a case insensitive one).  The pathnames as specified to filter-repo must match how they were recorded in history (which may or may not match how they display in your directory listing in your working tree).  If files were recorded with different cases in different commits, then you need to specify each one you want to keep (or you could use --filename-callback if you just wanted to write the code logic to pick the paths you want).  `git ls-tree -r $COMMIT` or `git log --name-status --all` might help you determine the filenames as recorded.

Also, I'm curious what the format of the file is that you're passing to --paths-from-file.  It looks like my code handles both LF and CRLF, but I'm guessing if you managed to save some file in UTF-16 then filter-repo would be misled into assuming you've got all kinds of NUL bytes in your filenames.  I think git-for-windows and perhaps python have various things that autoconvert to UTF-8, but I'm not at all sure how that works.  I suspect the issues above are much more likely, but mention this just in case there's something weird with your file.

**Comment by richardck** [comment] 2020-04-23 14:35
Hello Elijah,
Thanks for engaging with me on this issue.
Project priorities have meant that following a spurt of activity on Tuesday to try to get this sorted I'm not able to give it more time for the time being.
After my initial posting on this issue I tried adding "glob:" to all the lines with '*' in them, but that failed to work in the same way - still only the "panels" folder is being processed.
Yes case is mixed - no, it isn't broken, that's what Windows does - it always has, and I expect it always will, and there are a lot of people using it quite satisfactorily, and yes I realize that as a Linux developer you've had to sign the pledge to snipe at Windows on every possible occasion ;-)
The pathnames in my project are mixed but the way I've used them in the config file matches how they are found in the project, however I will look more carefully in the "filter-repo/analysis" folder to check they do exactly match.
My filter params file is just a standard Windows file with CRLF line-endings.  I would assume the Windows build of Python will know how lines are structured - actually I see from the code that you use rstrip set to remove CR and LF so I would assume it gets sensible results from sensible input.
I don't think my project has any utf-16 in use; I don't think we have historically been sophisticated enough to do so.
I will perhaps also try it with --debug to see if that gives me any more help.  My experience is in C/C++ and I know next to nothing about Python so it'll take me a it of work to understand what the program is doing.
Anyway, thanks for your help and I'll get back to you once I've had time to review the issues mentioned.
Regards,
Richard.

**Comment by newren** [comment] 2020-04-23 15:03
Another possibility for investigation: If you happen to have a repo I can clone (can be the real one or just an example one that is similar and exhibits the problem for you) and an example file you are passing to --paths-from-file, then I'll be happy to try to test it out on both Linux and Mac.  One of the partitions on my work laptop (the Mac) happen to be broken too (and, is in fact, even more broken).  If it really is case-sensitivity of filenames in history, I should be able to duplicate on either OS.  If it's something Windows specific such that I can't reproduce, having me test should at least help us narrow down the possibilities.  Just let me know.

Oh, and I think you misunderstood.  It's not that I need to snipe at Windows on every possible occasion; it's that certain forms of brokenness drive me crazy and I snipe at those, regardless of platform (treating filenames as anything other than a stream of bytes is one such thing, and means that case-insensitivity is bad and unicode normalization is even worse).  Also, the fact that people can use something "satisfactorily" by no means serves as a counter-example to things being broken -- as a former colleague of mine once said, "Software is like the human body.  There can be all kinds of things wrong with it and it still basically functions."  :-)

**Comment by newren** [comment] 2020-05-25 19:45
I just had a separate report about problems with --paths-from-file, in particular when combining filtering with renaming options; the renames would always get dropped.  I just pushed a fix for this.  Any chance you could retry with the newer version -- one that includes commit df6c8652a2 (filter-repo: fix ugly bug with mixing path filtering and renaming, 2020-05-25)?

And if it doesn't fix your case, any extra details you could provide for me to try to dig into your case would be appreciated.  Thanks!

**Comment by newren** [comment] 2020-06-01 15:05
I'm going to go ahead and close out since I haven't heard back for over a month.  I understand things can get busy sometimes, though, so if you can reproduce with the newest version and can provide some details about the different issues you said you'd review, please feel free to reopen.

**Closed by newren** 2020-06-01 15:05 UTC

**Comment by richardck** [comment] 2020-06-03 08:42
I'm sorry I didn't get back to you on this in a timely way.  I had meant to find an opportunity to try it and then reply but I've been stuck in another area and haven't had the time.  
Yes I will try it once I get a chance to get back to the original project.  I'll reopen if appropriate.
Thank you for engaging with me on this, and apologies again for my lack of communication.
