### ISSUE TITLE
fatal: cannot lock ref 

### ISSUE THREAD

**Issue by tbergstedt** [newren/git-filter-repo#325] opened 2022-01-17 14:38 UTC
I am unable to make this command work. I've tried syntax 
```
git filter-repo --path buildtools/definitions/ --path buildtools/policies/ --path buildtools/sanityChecks/ --path buildtools/utils/ --to-subdirectory-filter devops --tag-rename '':'devops-'
```

Whatever I try, I receive a 
```
fatal: cannot lock ref  'refs/heads/Releases/a-release-branch: Unable to create 'C:/git/TMP_repo/.git/refs/head/Releases/a-release-branch.lock': File exists`. 

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
git update-ref failed; see above
```
But there never is such a file, and I've tried right after a machine restart just to make certain that no other Git process is running (and checked running processes as well). 

I've also tried using '\\' for paths, tried skipping subdirectory-filter parameters and tag-rename, to no avail.

The actual branch given in the error also sometimes changes, but the error is the same.

**System info**
**OS**: Windows 10 Pro 10.0.18363
**git-filter-pro**: 2.34.0
**Git**: 2.33.0
**Git-LFS**: 2.13.3

**Comment by newren** [comment] 2022-02-09 20:30
This is a duplicate of #48 (and #156).  See the comments in those reports.  You both have repos with branches that differ only in case from each other, and you have a case insensitive filesystem preventing anything from locking both.  You can either delete some of those branches, or run git-filter-repo on a case sensitive filesystem where the filtering will work.

(There's some philosophical questions here about whether this is a bug in your filesystem, whether it's also a bug in Git for not being able to work around common filesystem bugs (though reftable has been in progress for a few years and should eventually workaround your broken filesystem), and perhaps whether it's a bug in git-filter-repo for not having a clean way to detect when git-fast-import dies in this ugly manner and attempt to report a clearer error message (though it's not clear how much could really be done here).)

**Closed by newren** 2022-02-09 20:30 UTC
