### ISSUE TITLE
Case-insenstive APFS volumes causing refs lock problem?

### ISSUE THREAD

**Issue by jmataraz** [newren/git-filter-repo#572] opened 2024-06-20 17:22 UTC
Attempting to use current main (65c5863) of `git-filter-repo` on macOS with a case-INsensitive volume kept throwing errors:
```
fatal: cannot lock ref 'refs/heads/Release/R18A': Unable to create '/Volumes/Sources/MyProj/.git/refs/heads/Release/R18A.lock': File exists.
```
It would be a different file sometimes on rerun, but always the same error type.

On a whim, I created a Case-sensitive APFS volume, did another clone there, and the same command worked flawlessly.
The command I ran (not sure it matters) was `git-filter-repo --invert-paths --path-match=trash_this_path`

**Comment by newren** [comment] 2024-07-02 20:16
Yeah, duplicate of #48, #156, #325, #512, and #566 -- it's a well-known problem.  The issue is you have branches that differ only in case; if you don't touch those branches, git is fine, but it'll explode if you touch them and git-filter-repo by its design needs to touch them.  You can either use a sane filesystem (which you found out worked), or find out which branches exist (`git show-ref`), look for those that differ only in case, delete branches until you don't have such a conflict, and then run the repository filtering.

**Closed by newren** 2024-07-02 20:16 UTC
