### ISSUE TITLE
Renaming subdir to repo root dir causes BrokenPipeError

### ISSUE THREAD

**Issue by kimballa** [newren/git-filter-repo#356] opened 2022-03-19 20:45 UTC
I am trying to split up a monorepo (at https://github.com/kimballa/arduino-workspace) into several project-specific repos. The first of these projects is in the `makefiles` subdirectory of that repository. I tried to pull the contents of that subdirectory into the root dir of a new repo with the following command:

```
$ git-filter-repo --path makefiles/ --path-rename 'makefiles':'.' --path LICENSE.txt --path README.md \
    --path .gitignore  --force
```

This gave me an error message complaining about `.` as a directory:

```
Error: Invalid path component '.' found in 'makefiles:.'
```

I then tried deleting the `.`:

```
$ git-filter-repo --path makefiles/ --path-rename 'makefiles':'' --path LICENSE.txt --path README.md  \
   --path .gitignore  --force
```

...and I got an uncaught exception:

```
fatal: Empty path component found in input
fast-import: dumping crash report to .git/fast_import_crash_4968
Traceback (most recent call last):
  File "/home/aaron/bin/git-filter-repo", line 4004, in <module>
    main()
  File "/home/aaron/bin/git-filter-repo", line 4001, in main
    filter.run()
  File "/home/aaron/bin/git-filter-repo", line 3936, in run
    self._parser.run(self._input, self._output)
  File "/home/aaron/bin/git-filter-repo", line 1409, in run
    self._parse_commit()
  File "/home/aaron/bin/git-filter-repo", line 1260, in _parse_commit
    self._commit_callback(commit, aux_info)
  File "/home/aaron/bin/git-filter-repo", line 3483, in _tweak_commit
    if not self._prunable(commit, new_1st_parent,
  File "/home/aaron/bin/git-filter-repo", line 3239, in _prunable
    self._output.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

I can work around this with some `git mv` post-processing but I think this should ideally have better support for renaming-to-root, or at minimum catching the above exception and translating to a more graceful error message. Thanks for the tool, though -- powerful magic. Crash log file is attached.

[fast_import_crash_4968.txt](https://github.com/newren/git-filter-repo/files/8310095/fast_import_crash_4968.txt)

**Comment by k4rtik** [comment] 2022-05-23 15:22
Facing the same issue, it used to work fine last year around this time.

**Comment by newren** [comment] 2022-05-28 00:55
Yes, the problem is here:

`--path-rename 'makefiles':'.'`

Which says to change filenames like 
```
    makefiles/foo/bar/stuff.txt
    makfiles_are_fun.txt
```
to
```
   ./foo/bar/stuff.txt
   ._are_fun.txt
```

since it's doing a literal string replacement.  However, you can't create a literal directory named '.', so it dies.  And when you remove the '.', then the replacements become
```
   /foo/bar/stuff.txt
   _are_fun.txt
```

and the first of those paths is illegal since it says there should be a 'stuff.txt' in a 'bar' directory which is in a 'foo' directory, which is in a directory whose name is the empty string.

You need to instead use a trailing slash when renaming to the repo root directory, i.e. `--path-rename makefiles/:`.  I know, the documentation on this is problematic.

Anyway, this is a duplicate of #358, so I'll close out and we can track over there.

**Closed by newren** 2022-05-28 00:55 UTC
