### ISSUE TITLE
Empty target repository after filtering a directory

### ISSUE THREAD

**Issue by ichbinsteffen** [newren/git-filter-repo#294] opened 2021-10-19 12:49 UTC
I used the following command:

`git filter-repo --force --debug --source sourceRepo/mv/ --path sourceRepo/mv/DataSchema/ --target targetRepo/`

This was the output:

> ibs@PC:~/filter-repo$ git filter-repo --force --debug --source sourceRepo/mv/ --path sourceRepo/mv/DataSchema/ --target targetRepo/
[DEBUG] Passed arguments:
Namespace(analyze=False, blob_callback=None, commit_callback=None, debug=True, dry_run=False, email_callback=None, filename_callback=None, force=True, help=False, inclusive=True, mailmap=None, max_blob_size=0, message_callback=None, name_callback=None, no_ff=False, partial=True, path_changes=[('filter', 'match', b'sourceRepo/mv/DataSchema/')], preserve_commit_encoding=False, preserve_commit_hashes=False, prune_degenerate='auto', prune_empty='auto', quiet=False, refname_callback=None, refs=['--all'], repack=True, replace_refs=None, replace_text=None, reset_callback=None, source=b'sourceRepo/mv/', state_branch=None, stdin=False, strip_blobs_with_ids=set(), subdirectory_filter=None, tag_callback=None, tag_rename=None, target=b'targetRepo/', to_subdirectory_filter=None, use_base_name=False, version=False)
[DEBUG] Running: git -C sourceRepo/mv/ fast-export --show-original-ids --signed-tags=strip --tag-of-filtered-object=rewrite --fake-missing-tagger --reference-excluded-parents --use-done-feature --mark-tags --reencode=yes --all
  (saving a copy of the output at targetRepo/.git/filter-repo/fast-export.original)
[DEBUG] Running: git -C targetRepo/ -c core.ignorecase=false fast-import --force --quiet
  (using the following file as input: targetRepo/.git/filter-repo/fast-export.filtered)
Parsed 54680 commits
New history written in 1331.36 seconds; now repacking/cleaning...
[DEBUG] Running (in targetRepo/): git reset --hard
[DEBUG] Running (in targetRepo/): git reflog expire --expire=now --all
[DEBUG] Running (in targetRepo/): git gc --prune=now
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), done.
Total 1 (delta 0), reused 0 (delta 0)
Completely finished after 1334.14 seconds.

Looks good so far... but:

`ibs@PC:~/filter-repo/targetRepo$ ls -A`
`.git`
`ibs@PC:~/filter-repo/targetRepo$`

After running this, as you can see the target repository contained nothing but the ".git" folder. 
I ran into the same problem on windows and linux. The output above is from the past run under linux (wsl ubuntu, git 2.25.1). 
I can read into targetRepo/.git/filter-repo/fast-export.filtered (which is huge btw.) and see lots of the actual content source code of the repo, but thats about it. Git status reveals the obvious:

>On branch master
No commits yet

As empty as before.
Am I doing something wrong? Why am I getting an empty repo?

**Comment by newren** [comment] 2021-11-09 18:47
I think the problem here is that --path is supposed to operate on files as found in the git repository, not relative to whatever directory you original ran from (i.e. filenames that `git [-C gitrepo] log --name-only` would have shown or `git [-C gitrepo] ls-files` would have shown).  But let me ask a few more detailed questions...

Is sourceRepo/mv/ actually a git repository (i.e. does sourceRepo/mv/.git exists)?  If not, perhaps your --source should have been sourceRepo?

Also, I'm assuming targetRepo/ is a git repository, i.e. targetRepo/.git exists before your command.

Now, what kind of files exist under sourceRepo/mv/?  (Or is it just sourceRepo/?)  Do you actually expect to see files underneath that directory named sourceRepo/mv/DataSchema/...?  If so, that would suggest that the directory you ran your filter-repo command from had files named sourceRepo/mv/sourceRepo/mv/DataSchema/... within them.  The fact that targetRepo ends up empty suggests you don't have such paths.

**Comment by newren** [comment] 2022-06-04 05:17
@johentsch: That seems like a different issue to me; the original reporter clearly seemed to have problems specifying paths as stored in git based on using --source and --target and had no renaming going on.  You had an example where you claimed you had problems without either --source or --target, but you were using path renaming.  It's possible the issues are related, but we don't have much in the way of evidence and never got more info from @ichbinsteffen on their issue.

Could you open a separate issue for your problem?  And let's focus on the "git filter-repo --subdirectory sub1/sub2" without the --source and --target arguments until we understand just that issue.  Note, though, that I can't reproduce your problem.  `git filter-repo --subdirectory-filter sub1/sub2` works great for me on a repo where `git log -- sub1/sub2` shows lots of commits, and will retain those commits in the filtered solution (and mostly just those commits, but likely also some merge commits needed to flesh out the full topology).  It'd be great if you could link to an example repo and use exact commands (i.e. not "sub1/sub2" but the real directory names) and compare the output of "git rev-list --count HEAD -- sub1/sub2" before the filtering with "git rev-list --count HEAD" after filtering.

**Comment by ichbinsteffen** [comment] 2022-06-04 23:53
Hey @newren,
I'll report back on Tuesday. In the end I got it working somehow and the working script I use is on my computer at work. So I'll report back on what I did differently to get it to work as intended.

**Comment by vunhatchuong** [comment] 2023-04-15 06:50
I have the same problem of empty repo when uses on Windows. Installed with `pip` in conda env. So I open up WSL2, install through `apt` and the same command works.

**Comment by newren** [comment] 2024-07-02 15:55
@vunhatchuong : 

> I have the same problem of empty repo when uses on Windows. Installed with pip in conda env. So I open up WSL2, install through apt and the same command works.

That sounds like one of the PowerShell issues we have in various other open issues; PowerShell sounds somewhat problematic.  Glad WSL2 worked for you, but we're taking this issue off-topic.

> I'll report back on Tuesday. In the end I got it working somehow and the working script I use is on my computer at work. So I'll report back on what I did differently to get it to work as intended.

Not sure which Tuesday was intended, but I'm pretty sure there's no point after a few years continuing to wait.  So let's close this one out.

**Closed by newren** 2024-07-02 15:55 UTC
