### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by thebravoman** [newren/git-filter-repo#95] opened 2020-05-19 04:58 UTC
Using git 2.26, python3.7

Got an error on the first command. 

Trying 
```bash
$ git filter-repo --path app/themes/ 
Traceback (most recent call last):
  File "/home/user/local/bin/git-filter-repo", line 3927, in <module>
    filter.run()
  File "/home/user/local/bin/git-filter-repo", line 3849, in run
    self._run_sanity_checks()
  File "/home/user/local/bin/git-filter-repo", line 2848, in _run_sanity_checks
    RepoFilter.sanity_check(self._orig_refs, is_bare)
  File "/home/user/local/bin/git-filter-repo", line 2880, in sanity_check
    abort(_("expected freshly packed repo"))
  File "/home/user/local/bin/git-filter-repo", line 2860, in abort
    if os.path.isdir(output):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Also trying the example from the main page

```bash
$ git filter-repo --path app/themes/ --to-subdirectory-filter app/themes2
Traceback (most recent call last):
  File "/home/user/local/bin/git-filter-repo", line 3927, in <module>
    filter.run()
  File "/home/user/local/bin/git-filter-repo", line 3849, in run
    self._run_sanity_checks()
  File "/home/user/local/bin/git-filter-repo", line 2848, in _run_sanity_checks
    RepoFilter.sanity_check(self._orig_refs, is_bare)
  File "/home/user/local/bin/git-filter-repo", line 2880, in sanity_check
    abort(_("expected freshly packed repo"))
  File "/home/user/local/bin/git-filter-repo", line 2860, in abort
    if os.path.isdir(output):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

Event trying
```bash
$ git filter-repo --path app/themes/ --to-subdirectory-filter my-module --tag-rename '':'my-module-'
Traceback (most recent call last):
  File "/home/kireto/local/bin/git-filter-repo", line 3927, in <module>
    filter.run()
  File "/home/kireto/local/bin/git-filter-repo", line 3849, in run
    self._run_sanity_checks()
  File "/home/kireto/local/bin/git-filter-repo", line 2848, in _run_sanity_checks
    RepoFilter.sanity_check(self._orig_refs, is_bare)
  File "/home/kireto/local/bin/git-filter-repo", line 2880, in sanity_check
    abort(_("expected freshly packed repo"))
  File "/home/kireto/local/bin/git-filter-repo", line 2860, in abort
    if os.path.isdir(output):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Update 1:**
I saw the error in the code that the repo should be freshly packed. "Make sure repo is fully packed, just like a fresh clone would be." This repo I am working on was just checkout. 

Doing 
```bash
$ git repack
Enumerating objects: 8513, done.
Counting objects: 100% (127/127), done.
Delta compression using up to 4 threads
Compressing objects: 100% (122/122), done.
Writing objects: 100% (127/127), done.
Total 127 (delta 1), reused 0 (delta 0), pack-reused 0
```
and then again 
```bash
$ git filter-repo --path app/ --to-subdirectory-filter my-module --tag-rename '':'my-module-'
Traceback (most recent call last):
  File "/home/kireto/local/bin/git-filter-repo", line 3927, in <module>
    filter.run()
  File "/home/kireto/local/bin/git-filter-repo", line 3849, in run
    self._run_sanity_checks()
  File "/home/kireto/local/bin/git-filter-repo", line 2848, in _run_sanity_checks
    RepoFilter.sanity_check(self._orig_refs, is_bare)
  File "/home/kireto/local/bin/git-filter-repo", line 2880, in sanity_check
    abort(_("expected freshly packed repo"))
  File "/home/kireto/local/bin/git-filter-repo", line 2860, in abort
    if os.path.isdir(output):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

```

**Update 2**:
Tried to create a new project, add a remote, checkout from remote and filter 
```bash
$ git init
$ git add .
$ git commit -m "initial commit"
$ git remote add origin repo_url
$ git pull origin dev
$ git checkout dev
$ git filter-repo --path app/themes
Traceback (most recent call last):
  File "/home/user/local/bin/git-filter-repo", line 3927, in <module>
    filter.run()
  File "/home/user/local/bin/git-filter-repo", line 3849, in run
    self._run_sanity_checks()
  File "/home/user/local/bin/git-filter-repo", line 2848, in _run_sanity_checks
    RepoFilter.sanity_check(self._orig_refs, is_bare)
  File "/home/user/local/bin/git-filter-repo", line 2880, in sanity_check
    abort(_("expected freshly packed repo"))
  File "/home/user/local/bin/git-filter-repo", line 2860, in abort
    if os.path.isdir(output):
  File "/usr/lib/python3.7/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Update 3**
I managed to get it working with --force, but is this the expected way or there is an underlying issue.

**Comment by newren** [comment] 2020-05-19 06:23
Thanks for the report!  Indeed, there's a bug in the change I pushed on Friday, and I just pushed commit 3dfaf3874e (filter-repo: fix --no-local error when there is no remote, 2020-05-18) to fix this.

Your updates 1 & 2 surprise me a bit, though.  What's the output of `git count-objects -v` in that repo?

**Comment by thebravoman** [comment] 2020-05-19 08:14
Just after checkout 
```
$ git count-objects -v
count: 0
size: 0
in-pack: 121299
packs: 1
size-pack: 220129
prune-packable: 0
garbage: 0
size-garbage: 0
```

**Comment by newren** [comment] 2020-05-19 15:24
That looks like a nice, freshly packed repo.  Do you get any error now with the newest version of filter-repo?

**Comment by thebravoman** [comment] 2020-05-19 17:14
Two parts. Yes and no

Here are the commands with the output

```bash
$ cd tmp/
$ git init .
# elvis2 is the machine. my_remote is the name of the remote
# my_project is the name of the project
$ git remote add my_remote git@elvis2:my_project 
$ git pull my_remote dev
$ git checkout dev
Branch 'dev' set up to track remote branch 'dev' from 'my_remote'.
Switched to a new branch 'dev'
$ git status
On branch dev
Your branch is up to date with 'my_remote/dev'.
nothing to commit, working tree clean
$ git filter-repo --path app/themes
Aborting: Refusing to overwrite repo history since this does not
look like a fresh clone.
  (expected one remote, origin)
To override, use --force.
```
So I am not sure if this is now the expected result?

It is true that I do not have 'origin'. My remote is called 'my_remote' because if stopped using 'origin' long ago for reasons that I could get into details if needed, but they are connected with the way our production works.

**Comment by newren** [comment] 2020-05-19 17:29
> It is true that I do not have 'origin'. My remote is called 'my_remote' because we stopped using 'origin' long ago for reasons that I could get into details if needed, but they are connected with the way our production works.

Ah, gotcha!  Yeah, there is no way in git for someone to check "Is this repository a fresh clone?"  Since filter-repo does irreversible rewriting of history, though, I really really want to avoid changing for which the user doesn't have a good backup.  So, I found approximately a dozen things that happen to be true of brand new clones, and I check for all of those.

My checks can have both false positives and false negatives (e.g. in your case you have a backup of the stuff you are about to run filter-repo on, but there's no way for filter-repo to know that; conversely, someone could look at all the reasons I abort in my safety checks and just tweak their non-backed-up repository to match all those conditions.  In fact, I've done that in testcases.)  However, in practice the safety checks I have in place seem to be really good at avoiding people accidentally running filter-repo on a repository that they shouldn't be running it on.  It even caught me once when I did mean to run filter-repo but was in a different directory than I thought I was.

Anyway, if you're not going to use the normal "git clone" mechanism to get a copy of your repo to run filter-repo on (and don't want to tweak it to make it look the same, such as renaming your remote to origin), then yes, you'd be expected to pass "--force" to make it override the safety checks.  If you have a backup of your repo, then adding --force is fine, because making sure you have a backup of the repo you are running in is the sole purpose of those checks.

Glad that we got you past the TypeError problems; thanks for reporting that.

I'm assuming this answers your questions and we're good to close this out.  Is that fair?

**Comment by thebravoman** [comment] 2020-05-19 20:23
Yes, I am perfectly fine to close. 

The behavior seems logical. I would suggest that your reply should be part of the readme of filter-repo and it should be somewhere at the top in a section called - "# Goals and architecture".

**Comment by thebravoman** [comment] 2020-05-19 20:32
@newren 
But the behavior of git filter-repo is not entirely in sync with your philosophy of never touch a thing.

Today I spend like half an hour and had to return the repo two tree times until I figured out that there is a --refs options to the command. 

Because I was doing filter-repo and it was filtering in all branches, even branches that are not in this origin and even branches that were not in an origin at all. So git filter-repo was actually destroying things that i would not expect it to destroy. 

I would expect to be in a branch and when I am in a branch and do filter-repo to filter only this branch and to have an option to tell it to filter in other branches. 

I know, it is called filter-repo, so it is quite obvious that it is filtering 'repos' and not branches, but if the philosophy is not to destroy things users do not intend to destroy than there should filtering just in the current branch with an option to filter in all branches.

**Comment by newren** [comment] 2020-05-19 22:28
> @newren
> But the behavior of git filter-repo is not entirely in sync with your philosophy of never touch a thing.

Where did I espouse such a philosophy?  That doesn't sound familiar at all.

> I would expect to be in a branch and when I am in a branch and do filter-repo to filter only this branch and to have an option to tell it to filter in other branches.
> 
> I know, it is called filter-repo, so it is quite obvious that it is filtering 'repos' and not branches, but if the philosophy is not to destroy things users do not intend to destroy than there should filtering just in the current branch with an option to filter in all branches.

The fact that filter-repo filters the whole repository is much more than the name, and was by no means an accident of implementation.  Avoiding mixing old and new history was one of the primary original design goals of filter-repo, so it's very much by design that those who want to only rewrite on branch or a few recent commits have to use special options.  In fact, whole-repository rewriting requires extra effort that branch-specific thinking will tend to overlook and not even support, and is one of the (many) reasons that filter-branch is so broken and dangerous for users to use.  I got tired of people rewriting one branch, then merging rewritten and unrewritten branches together to end up with two copies of nearly every commit, then coming to me wondering what was wrong.  Of course my tool is going to avoid that problem.

There are totally valid usecases where users only want to rewrite a single branch or some of the latest commits on a couple branches, but that's why --partial and --refs exist (which, by the way, come with big warnings about how using them could result in users accidentally mixing old and new history together).

So, the tool is named "filter-repo", the first sentence of the manual says "Rapidly rewrite *entire* repository history", there is a bullet point early in the manual that says "stripping of original history to avoid mixing old and new history" is something that is automatically taken care of for the user, both --partial and --refs are provided with warnings, etc.  In fact, under the "issues specific to filter repo" near the end of the manual, I wrote:

`Partial-repo filtering, while supported, runs counter to filter-repo’s "avoid mixing old and new history" design. This support has required improvements to core git as well (e.g. it depends upon the --reference-excluded-parents option to fast-export that was added specifically for this usage within filter-repo). The --partial and --refs options will continue to be supported since there are people with usecases for them; however, I am concerned that this inconsistency about mixing old and new history seems likely to lead to user mistakes. For now, I just hope that long explanations of caveats in the documentation of these options suffice to curtail any such problems.`

So I absolutely won't be changing that default.

**Comment by newren** [comment] 2020-05-19 22:34
> Yes, I am perfectly fine to close.
> 
> The behavior seems logical. I would suggest that your reply should be part of the readme of filter-repo and it should be somewhere at the top in a section called - "# Goals and architecture".

I added a "Fresh clone safety check and --force" section to the manual, and linked to it from the description of the --force option.  See commit 1e2d0e91cb (Documentation: add more detailed explanation of safety checks and --force, 2020-05-19).  I'll close this out.


Thanks for reporting the TypeError issue!

**Closed by newren** 2020-05-19 22:34 UTC

**Comment by thebravoman** [comment] 2020-05-20 04:00
Thanks @newren 

> Where did I espouse such a philosophy? That doesn't sound familiar at all.

This was how I understood "I really really want to avoid making changes to a repo for which the user doesn't have a good backup." It got me by surprise and as far as I know the people I work closely with it will get them also. If other people also get surprised I am sure that a small example on the readme would make it very clear. 

I think there really is no need change the default. Yesterday I managed to do a day of filter-branch work in an hour with filter-repo. This only shows that the decisions made by you are like 20 times better. Thanks
