### ISSUE TITLE
[Feature request] Option to automatically follow file renames for --path

### ISSUE THREAD

**Issue by zypA13510** [newren/git-filter-repo#265] opened 2021-07-01 09:45 UTC
Say I have this in git history (R denotes renaming/moving):
```
┌ 9000ef (+-) newName.txt
├ cd5678 (R)  oldName.txt => newName.txt
├ 1234ab (+)  oldName.txt
```

Currently, if I run `git-filter-repo --path newName.txt`, the new repo is going to contain only:
```
┌ replace/9000ef (+-) newName.txt
├ replace/cd5678 (+)  newName.txt
```

And the only way to make it contain the history of `oldName.txt` as well (that I know of) would be to run `git-filter-repo --path newName.txt --path oldName.txt`. Now, there are a few problems with this:

1. There are hundreds of commits in between, and I may have hundreds of files, also I may not necessarily know if any of them had been renamed/moved in the past. I can only search manually for each file to see if it happened in the past. This is repetitive and tiresome, not to mention that a file may have been moved multiple times.
2. Theoretically, if I have a new file with the exact same name created after the rename (like illustrated below), my understanding is that the command is not going to work as I would expect:
    ```
    ┌ 555555 (+)  oldName.txt
    ├ 9000ef (+-) newName.txt
    ├ cd5678 (R)  oldName.txt => newName.txt
    ├ 1234ab (+)  oldName.txt
    ```

Sorry if I've missed something obvious, this looks like a must-have for rewriting git history.

P.S. Please forgive me if this is a duplicate. I've tried to search "rename" and "move" but due to the similarity with `--path-rename`, there are a lot of issues. I may have missed another similar issue.

**Comment by metok** [comment] 2021-08-11 14:59
This feature is exactly what I need :)
And probably everybody else, who is carving out a monolith..

**Comment by larsgrefer** [comment] 2021-08-11 16:38
This seems to be a duplicate of https://github.com/newren/git-filter-repo/issues/25

**Comment by newren** [comment] 2021-08-11 17:52
Indeed, it's a duplicate; thanks for finding the old report, @larsgrefer.  The hint in #25 about using --analyze to generate a list of renames (though based on various heuristics, and note that it doesn't attempt copy detection) may be helpful, as that gives you a way to pick up what files you want were renames of in history.

**Closed by newren** 2021-08-11 17:52 UTC

**Comment by newren** [comment] 2021-08-11 17:54
I should also note that I totally understand that people want this and I wanted it myself, but the fact that (a) it involves lots of heuristics and (b) even git log --follow can't handle multiple paths still these days makes it something that isn't very easy to get into place and will always be slightly suboptimal.  I'd want to fix (b) before fixing this issue, so it might be a while...sorry.

**Comment by wetted** [comment] 2021-08-11 18:04
I am breaking apart a 20 yr old legacy monolithic project of some 3M LOC. Not only have their been lots of file renames through refactoring, but also complete source tree restructuring as we have migrated across build tools and conventions. 

Using `--analyze` can be painful (our renames.txt file has nearly 70k lines), but it is key to getting this done correctly (we have mandate to retain commit history).
