### ISSUE TITLE
for now, I've found that I can recover the notes from the replace refs:

### ISSUE THREAD

**Issue by Bubbap89** [newren/git-filter-repo#395] opened 2022-10-02 07:05 UTC
for now, I've found that I can recover the notes from the replace refs:

```sh
git for-each-ref refs/replace/ --format='%(objectname) %(objecttype) %(refname:lstrip=2)' \
| while read new type old; do
    if [ "$type" != "commit" ]; then
        exit 1
    fi

    git notes copy $old $new
    git notes git for-each-ref refs/replace/ --format='%(objectname) %(objecttype) %(refname:lstrip=2)' \
| while read new type old; do
    if [ "$type" != "commit" ]; then
        exit 1
    fi

    git notes copy $old $new
    git notes remove $old
👍 $old
done
```

_Originally posted by @glensc in https://github.com/newren/git-filter-repo/issues/22#issuecomment-558693518_

**Comment by newren** [comment] 2022-10-12 07:16
No point having two issues open about the same thing.  This is clearly just a duplicate of #22.

**Closed by newren** 2022-10-12 07:16 UTC
