### ISSUE TITLE
Adding submodules to each commit

### ISSUE THREAD

**Issue by zabeloliver** [newren/git-filter-repo#14] opened 2019-11-13 11:00 UTC
Hello, i'm looking to migrate old svn repos which heavily uses svn:externals to Git. Since there is no official solution to this problem we are looking for other solutions. We came up with the following idea: Importing svn-repo to git with subgit (www.subgit.com). This tool has an option to add a file .gitsvnextmodules to each commit which includes all all svn:externals info such as path and revision. We now have the idea to loop trough this repo and change each commit to add submodules for each entry in the .gitsvnextmodules file. This would end up in a equivalent Git repo to the svn repo.

Would this be possible with your tool? Is there perhaps another way of achieving this particular problem? 

Thank you in advance for your answer!
Best Regards, 
Oliver

**Comment by newren** [comment] 2019-11-13 18:06
It should be possible, it's just some work.  While I've heard of svn:externals, I'm not familiar with them, but as far as I can tell from what you've written the basic idea would go like this:

  - First convert the submodule(s).  For each, you need to keep a mapping from svn revision to git commit id.
  - When converting the supermodule, for each commit you need to look at the .gitsvnextmodules file to see what submodules are wanted -- both their path name and the svn revision.  For each submodule, get the mapping from svn revision to git commit id, then create a FileChange object (e.g. `FileChange(b'M', pathname, commit_id, b'160000'` where 160000 is the filemode that git uses for submodules) and add it to commit.file_changes.
  - Since git submodules also depend on a toplevel .gitmodules file, you'll also need to create that, either on the fly as submodules are added, or maybe just create it in the initial commit.  Not being a heavy user of submodules, I don't know if git gets confused if you have a .gitmodules file in a version but don't have any actual submodules yet, so you may need to play with this.  If it doesn't get confused, just adding the .gitmodules in the root commit(s) might be easiest.
  - And, just to be tidy, you may want to remove the .gitsvnextmodules file from the commit as you go too.

This could possibly all be crammed into a --commit-callback, but it might be nicer (and more reusable) to create a full script like those in contrib/filter-repo-demos/.

Some additional pointers:

  - the contrib/filter-repo-demos/lint-history script shows an example of how to add completely new files to the stream and make files in a commit reference them.  That may be helpful for creating the .gitmodules file, even if it'll be a new file for you rather than a modification of an existing file.
  - the contrib/filter-repo-demos/insert-beginning script shows an example of how to add extra files into a commit (in particular, appending to commit.file_changes).  It also shows how you could tweak the "first commit" (or first commits) in history.  In combination with the info from the lint-history script, this might be useful for your new .gitmodules file.  Also, the appending to commit.file_changes is helpful for getting the submodule FileChange object added.
  - the contrib/filter-repo-demos/clean-ignore script might be helpful in terms of how to get rid of unwanted changes (stripping files from commit.file_changes) to enable you to remove the .gitsvnextmodules files if you wanted to include that in the same filtering run.

If you give this a shot, I'm curious to hear how it works out.  Feel free to ping if you run into roadblocks.  And if it works out and you're willing to share the commands or script you come up with, it could be an awesome example to add to the contrib/filter-repo-demos/ directory (even if you have a few hacks, caveats or whatever; that directory already comes with a disclaimer).

**Comment by zabeloliver** [comment] 2019-11-14 09:38
Hi Elijah, 

first of all, thank you very much for this comprehensive post! I think this will guide us definitively into the right direction and we will of course share our experience and scripts with you!

Best regards, 
Oli

**Comment by newren** [comment] 2019-12-27 00:12
I'm going to go ahead and close this out just to keep the issues list tidy (though I've marked it with the contrib-candidate label so I can others can find it).  If you do come up with some scripts or have further questions, please do ping.  You can feel free to reopen, or if the issue is separate enough, just open a new issue.  Thanks!

**Closed by newren** 2019-12-27 00:12 UTC
Labels: contrib-candidate

**Comment by jahess** [comment] 2020-08-26 01:15
I've started an attempt.

First some assumptions / observations that I hope are correct and will hold:

1)  No other filter repo operations are going on except a single submodule extraction.  If those are necessary to make the separation "clean," those other operations should precede the actual submodule extraction.
2)  The extraction is for "all history."
3)  Every change in a submodule will produce a commit in the parent repository.  This commit could be just an updated submodule reference, or an updated submodule reference AND a mix of changes to possibly unrelated files in the parent repository.

The two inputs to the "filter-submodule" python script would be the parent repository "submodule-path" and the resulting extracted "submodule" name.  The submodule location reference will be relative to the parent repository as "../<submodule name>"

There is a FilterSubmodule class.  For now, it contains a FILE * to receive the fast export data for the submodule.  And it contains the commit filter for the parent repository.

An instance of RepoFilter is created for the parent repository.  It is passed the commit filter from FilterSubmodule.  run is called on the instance of RepoFilter.

I decided to start with the details of the submodule extraction.  I had thought about using a second RepoFilter to collect the submodule changes but... RepoFilter seemed overkill and it was hard to know how much of it to use or subvert.  RepoFilter seems both input and output and I only think I need output.  After seeing that the different fast export objects have a dump call, I decided to try calling commit.dump to that FILE *.  Currently I have a file that has commit objects and the files associated with those commits are the correct ones.  The paths that appear have the pre submodule split prefix but I'm guessing I just need to remove those prefixes from the file_changes before calling dump.  I also see mark and data directives but no actual file content data.

With all that setup my current questions:

1)  Any reservations on my assumptions?
2)  Any thoughts on my decision to use a FILE * for the submodule fast export rather than a second instance of FilterRepo?  I'm obviously missing the calls to dump the mark / data blobs.  I have spent some time looking at FilterRepo::_tweak_commit but being new to the code I'm not sure what is important and what can safely be skipped in FilterSubmodule::fixup_commit because of my assumptions.

FWIW, after I get a fast export file for the submodule that might work, I will try fast import on it.  After that works I will add the submodule reference to the fixup_commit on the parent repository FilterRepo instance.

**Comment by marcows** [comment] 2022-10-05 22:33
Hi Elijah, activity after a long time of silence here!

Oliver, the issue author, was a colleague of mine, but unfortunately doesn't work in our company anymore.

I just sent a patch out to the mailing list:
https://marc.info/?l=git&m=166500551728567&w=2

Living in this branch in my fork:
https://github.com/marcows/git-filter-repo/tree/svnext-conv

But these references are rather for you if interested, Oliver! Best wishes :-)

**Comment by glensc** [comment] 2022-10-06 03:47
@marcows why share branch if you could just easily send a PR?

**Comment by newren** [comment] 2022-10-06 04:05
@marcows : As commented on your patch submission, I've included it.  Thanks for submitting it!  I hope my comments from nearly three years ago were helpful, because I don't anymore remember any of the svn externals stuff I apparently looked up at the time.

**Comment by glensc** [comment] 2022-10-06 04:45
git commit of the adding for posterity:
- https://github.com/newren/git-filter-repo/commit/b164ffc988c7a0e18aaad7fbf7ddc29d3beb85c0

**Comment by marcows** [comment] 2022-10-06 08:40
@glensc I didn't open a PR because Elijah prefers patches to the mailing list. I shared the branch for Oliver, but will delete it now that it is already included.

**Comment by marcows** [comment] 2022-10-06 08:40
@newren Many thanks for inclusion! Your comments were pretty helpful and it's very motivating to get such comprehensive replies as @zabeloliver pointed out already.
